In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("SaleCleanForAnalysis.csv")

df.head()

,longitude,latitude,transaction_type,price,property_type,property_subtype,seller_id,postal_code,date_of_construction,property_condition,...,availability,province,street,street_number,garage,land_surface,energy_consumption,garden,balcony,swimming_pool
0,4.387667,50.846952,Sale,395000,Appartment,Duplex,46453,1000,1900.0,Excellent,...,On contract,Brussels,rue des patriotes,9.0,NaN,NaN,NaN,NaN,NaN,NaN
1,4.376693,50.823572,Sale,465000,Appartment,Flat,44165,1050,1959.0,Fully renovated,...,On contract,Brussels,rdpt de l'etoile,5.0,NaN,NaN,12178.0,NaN,NaN,NaN
2,4.341528,50.810316,Sale,190000,Appartment,Flat,46535,1180,NaN,To be renovated,...,Immediately,Brussels,rue des glaïeuls,17.0,NaN,NaN,NaN,NaN,NaN,NaN
3,4.333333,50.800000,Sale,155000,Appartment,FlatStudio,48985,1180,1978.0,Excellent,...,NaN,Brussels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.400549,50.850183,Sale,329000,Appartment,Flat,46371,1030,1959.0,Normal,...,NaN,Brussels,avenue lacomblé,14.0,1.0,NaN,NaN,NaN,True,NaN

In [2]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   longitude             9709 non-null   float64
 1   latitude              9709 non-null   float64
 2   transaction_type      9712 non-null   str
 3   price                 9712 non-null   int64
 4   property_type         9712 non-null   str
 5   property_subtype      9712 non-null   str
 6   seller_id             9712 non-null   int64
 7   postal_code           9712 non-null   int64
 8   date_of_construction  6280 non-null   float64
 9   property_condition    7516 non-null   str
 10  livable_surface       9154 non-null   float64
 11  number_of_bedrooms    9537 non-null   float64
 12  number_of_bathrooms   8780 non-null   float64
 13  elevator              7164 non-null   object
 14  terrace               3670 non-null   float64
 15  furnished             5954 non-null   object
 16  availability          5325 non-null   str
 17  province              9712 non-null   str
 18  street                7884 non-null   str
 19  street_number         7688 non-null   float64
 20  garage                3493 non-null   float64
 21  land_surface          5636 non-null   float64
 22  energy_consumption    2423 non-null   float64
 23  garden                2412 non-null   float64
 24  balcony               1019 non-null   object
 25  swimming_pool         1342 non-null   object
dtypes: float64(12), int64(3), object(4), str(7)
memory usage: 1.9+ MB

,longitude,latitude,price,seller_id,postal_code,date_of_construction,livable_surface,number_of_bedrooms,number_of_bathrooms,terrace,street_number,garage,land_surface,energy_consumption,garden
count,9709.000000,9709.000000,9.712000e+03,9712.000000,9712.000000,6280.000000,9154.000000,9537.000000,8780.000000,3670.000000,7688.000000,3493.000000,5636.000000,2423.000000,2412.000000
mean,4.587202,50.713370,4.038680e+05,37963.192236,4757.587315,1970.905732,169.400371,3.076125,1.387472,27.903542,73.518470,1.237332,1371.521114,53853.146925,997.560945
std,0.766890,0.378155,3.775355e+05,10444.316928,2718.506319,46.719683,116.880618,1.849597,0.918840,36.067537,523.744943,0.646661,4256.320333,48773.353880,3525.050758
min,2.576453,47.512679,0.000000e+00,0.000000,1000.000000,1554.000000,13.000000,0.000000,1.000000,1.000000,0.000000,1.000000,5.000000,1000.000000,1.000000
25%,4.239020,50.483333,2.299998e+05,33494.000000,2100.000000,1950.000000,99.000000,2.000000,1.000000,10.000000,11.000000,1.000000,256.000000,22911.500000,110.000000
50%,4.494500,50.765394,3.290000e+05,40435.500000,4500.000000,1975.000000,146.000000,3.000000,1.000000,20.000000,30.000000,1.000000,572.500000,44019.000000,338.500000
75%,5.231795,50.988216,4.650000e+05,44773.000000,6940.000000,2008.000000,200.750000,4.000000,2.000000,34.000000,74.000000,1.000000,1180.000000,72040.000000,833.250000
max,6.353742,51.472440,1.300000e+07,49351.000000,9991.000000,2028.000000,1565.000000,100.000000,23.000000,734.000000,40104.000000,10.000000,96317.000000,911959.000000,80000.000000

In [3]:
df.isna().sum()
df.isna().sum().sort_values(ascending=False)

balcony                 8693
swimming_pool           8370
garden                  7300
energy_consumption      7289
garage                  6219
terrace                 6042
availability            4387
land_surface            4076
furnished               3758
date_of_construction    3432
elevator                2548
property_condition      2196
street_number           2024
street                  1828
number_of_bathrooms      932
livable_surface          558
number_of_bedrooms       175
latitude                   3
longitude                  3
postal_code                0
seller_id                  0
property_subtype           0
price                      0
transaction_type           0
property_type              0
province                   0
dtype: int64

In [4]:
df.nunique()

longitude               7513
latitude                7494
transaction_type           1
price                   1389
property_type              2
property_subtype          15
seller_id                849
postal_code              897
date_of_construction     181
property_condition         9
livable_surface          555
number_of_bedrooms        25
number_of_bathrooms       15
elevator                   2
terrace                  137
furnished                  2
availability              64
province                  11
street                  5268
street_number            460
garage                     7
land_surface            2014
energy_consumption      2295
garden                   866
balcony                    2
swimming_pool              2
dtype: int64

In [5]:
df.shape

(9712, 26)

In [6]:
columns_to_drop = [
    "seller_id",
    "transaction_type",
    "street",
    "street_number",
    "postal_code",
    "balcony",
    "swimming_pool"
]
df = df.drop(columns=columns_to_drop)

In [7]:
df.columns

Index(['longitude', 'latitude', 'price', 'property_type', 'property_subtype',
       'date_of_construction', 'property_condition', 'livable_surface',
       'number_of_bedrooms', 'number_of_bathrooms', 'elevator', 'terrace',
       'furnished', 'availability', 'province', 'garage', 'land_surface',
       'energy_consumption', 'garden'],
      dtype='str')

In [8]:
df["energy_consumption"].isna().mean() * 100

np.float64(75.05148270181219)

In [9]:
df.shape

(9712, 19)

In [10]:
X = df.drop(columns="price")
y = df["price"]